### PR TITLE
Updated yaml.load call and fixed error with arrow date parsing in subreddit.py

### PR DESCRIPTION
**Pull request by biosafetylvl5**
With the most up to date python and package installed, I got the following error message:

```python
Traceback (most recent call last):
  File "/run/media/gwynu/gwynuArchive-Est/tools/redditPostArchiver-pl77/subreddit.py", line 755, in <module>
    appconfig = ApplicationConfiguration()
  File "/run/media/gwynu/gwynuArchive-Est/tools/redditPostArchiver-pl77/subreddit.py", line 49, in __init__
    self.__oldestdate = arrow.get('2005-06-23', 'YYYY-MM').timestamp
  File "/usr/lib/python3.8/site-packages/arrow/api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/arrow/factory.py", line 243, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "/usr/lib/python3.8/site-packages/arrow/parser.py", line 223, in parse
    raise ParserMatchError(
arrow.parser.ParserMatchError: Failed to match 'YYYY-MM' when parsing '2005-06-23'
```
 raised by `arrow.get('2005-06-23', 'YYYY-MM').timestamp` which I fixed by changing the format string from `'YYYY-MM'` to `'YYYY-MM-DD'`.

I also updated the deprecated call to `yaml.load()` with the [suggested alternative](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation) of `yaml.safe_load()`.

Thanks for all your work on this project!

### CODE REVIEW

**Comment by vitaliyhayda** [comment]
A bit unrelated - but I didn't find the Issues tab... I tried exporting the "ggjcz2" Reddit thread, but it only got 3,658 comments while the thread has over 18,100 already... Is that a Reddit limit? Thanks!

**Comment by biosafetylvl5** [comment]
hey @vitaliyhayda! it might be best to open an issue either here or on [my fork](https://github.com/biosafetylvl5/redditPostArchiver) - this thread is for the bug fix above and moving the conversation might get you a quicker response. (I'd also suggest posting a link to the ggjcz2 thread :eyes:)

**Comment by pl77** [comment]
@biosafetylvl5 Sorry about this!  I have two github accounts and realized I haven't logged in with this one in quite some time.  Just merged your pull request, my sincerest apologies.  I also opened an issues tab as I didn't realize it had been disabled. 

Thanks for all your work.  I have wanted to revisit this for a long time but other projects keep taking precedence so I deeply appreciate your efforts!

**Comment by biosafetylvl5** [comment]
No worries! Thanks for writing this in the first place, it's super handy :slightly_smiling_face:

**Pull request merged**
